/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedMachinesRouteImport } from './routes/_authenticated/machines'
import { Route as AuthenticatedKrishiBondhuRouteImport } from './routes/_authenticated/krishi-bondhu'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSellBuyerIdRouteImport } from './routes/_authenticated/sell.$buyerId'
import { Route as AuthenticatedMachinesIdRouteImport } from './routes/_authenticated/machines.$id'
import { Route as AuthenticatedSellListingListingIdRouteImport } from './routes/_authenticated/sell.listing.$listingId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachinesRoute = AuthenticatedMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKrishiBondhuRoute =
  AuthenticatedKrishiBondhuRouteImport.update({
    id: '/krishi-bondhu',
    path: '/krishi-bondhu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellBuyerIdRoute =
  AuthenticatedSellBuyerIdRouteImport.update({
    id: '/$buyerId',
    path: '/$buyerId',
    getParentRoute: () => AuthenticatedSellRoute,
  } as any)
const AuthenticatedMachinesIdRoute = AuthenticatedMachinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMachinesRoute,
} as any)
const AuthenticatedSellListingListingIdRoute =
  AuthenticatedSellListingListingIdRouteImport.update({
    id: '/listing/$listingId',
    path: '/listing/$listingId',
    getParentRoute: () => AuthenticatedSellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/machines': typeof AuthenticatedMachinesRouteWithChildren
  '/market': typeof AuthenticatedMarketRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/sell': typeof AuthenticatedSellRouteWithChildren
  '/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/machines': typeof AuthenticatedMachinesRouteWithChildren
  '/market': typeof AuthenticatedMarketRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/sell': typeof AuthenticatedSellRouteWithChildren
  '/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/_authenticated/machines': typeof AuthenticatedMachinesRouteWithChildren
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/sell': typeof AuthenticatedSellRouteWithChildren
  '/_authenticated/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/_authenticated/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/_authenticated/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/krishi-bondhu'
    | '/machines'
    | '/market'
    | '/profile'
    | '/schemes'
    | '/sell'
    | '/machines/$id'
    | '/sell/$buyerId'
    | '/sell/listing/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/krishi-bondhu'
    | '/machines'
    | '/market'
    | '/profile'
    | '/schemes'
    | '/sell'
    | '/machines/$id'
    | '/sell/$buyerId'
    | '/sell/listing/$listingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/krishi-bondhu'
    | '/_authenticated/machines'
    | '/_authenticated/market'
    | '/_authenticated/profile'
    | '/_authenticated/schemes'
    | '/_authenticated/sell'
    | '/_authenticated/machines/$id'
    | '/_authenticated/sell/$buyerId'
    | '/_authenticated/sell/listing/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines': {
      id: '/_authenticated/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthenticatedMachinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/krishi-bondhu': {
      id: '/_authenticated/krishi-bondhu'
      path: '/krishi-bondhu'
      fullPath: '/krishi-bondhu'
      preLoaderRoute: typeof AuthenticatedKrishiBondhuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/$buyerId': {
      id: '/_authenticated/sell/$buyerId'
      path: '/$buyerId'
      fullPath: '/sell/$buyerId'
      preLoaderRoute: typeof AuthenticatedSellBuyerIdRouteImport
      parentRoute: typeof AuthenticatedSellRoute
    }
    '/_authenticated/machines/$id': {
      id: '/_authenticated/machines/$id'
      path: '/$id'
      fullPath: '/machines/$id'
      preLoaderRoute: typeof AuthenticatedMachinesIdRouteImport
      parentRoute: typeof AuthenticatedMachinesRoute
    }
    '/_authenticated/sell/listing/$listingId': {
      id: '/_authenticated/sell/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/sell/listing/$listingId'
      preLoaderRoute: typeof AuthenticatedSellListingListingIdRouteImport
      parentRoute: typeof AuthenticatedSellRoute
    }
  }
}

interface AuthenticatedMachinesRouteChildren {
  AuthenticatedMachinesIdRoute: typeof AuthenticatedMachinesIdRoute
}

const AuthenticatedMachinesRouteChildren: AuthenticatedMachinesRouteChildren = {
  AuthenticatedMachinesIdRoute: AuthenticatedMachinesIdRoute,
}

const AuthenticatedMachinesRouteWithChildren =
  AuthenticatedMachinesRoute._addFileChildren(
    AuthenticatedMachinesRouteChildren,
  )

interface AuthenticatedSellRouteChildren {
  AuthenticatedSellBuyerIdRoute: typeof AuthenticatedSellBuyerIdRoute
  AuthenticatedSellListingListingIdRoute: typeof AuthenticatedSellListingListingIdRoute
}

const AuthenticatedSellRouteChildren: AuthenticatedSellRouteChildren = {
  AuthenticatedSellBuyerIdRoute: AuthenticatedSellBuyerIdRoute,
  AuthenticatedSellListingListingIdRoute:
    AuthenticatedSellListingListingIdRoute,
}

const AuthenticatedSellRouteWithChildren =
  AuthenticatedSellRoute._addFileChildren(AuthenticatedSellRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKrishiBondhuRoute: typeof AuthenticatedKrishiBondhuRoute
  AuthenticatedMachinesRoute: typeof AuthenticatedMachinesRouteWithChildren
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKrishiBondhuRoute: AuthenticatedKrishiBondhuRoute,
  AuthenticatedMachinesRoute: AuthenticatedMachinesRouteWithChildren,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedSellRoute: AuthenticatedSellRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
