/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedKrishiBondhuRouteImport } from './routes/_authenticated/krishi-bondhu'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSellIndexRouteImport } from './routes/_authenticated/sell.index'
import { Route as AuthenticatedMachinesIndexRouteImport } from './routes/_authenticated/machines.index'
import { Route as AuthenticatedSellBuyerIdRouteImport } from './routes/_authenticated/sell.$buyerId'
import { Route as AuthenticatedMachinesIdRouteImport } from './routes/_authenticated/machines.$id'
import { Route as AuthenticatedSellListingListingIdRouteImport } from './routes/_authenticated/sell.listing.$listingId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKrishiBondhuRoute =
  AuthenticatedKrishiBondhuRouteImport.update({
    id: '/krishi-bondhu',
    path: '/krishi-bondhu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellIndexRoute = AuthenticatedSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMachinesIndexRoute =
  AuthenticatedMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellBuyerIdRoute =
  AuthenticatedSellBuyerIdRouteImport.update({
    id: '/sell/$buyerId',
    path: '/sell/$buyerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMachinesIdRoute = AuthenticatedMachinesIdRouteImport.update({
  id: '/machines/$id',
  path: '/machines/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellListingListingIdRoute =
  AuthenticatedSellListingListingIdRouteImport.update({
    id: '/sell/listing/$listingId',
    path: '/sell/listing/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/machines/': typeof AuthenticatedMachinesIndexRoute
  '/sell/': typeof AuthenticatedSellIndexRoute
  '/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/market': typeof AuthenticatedMarketRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/machines': typeof AuthenticatedMachinesIndexRoute
  '/sell': typeof AuthenticatedSellIndexRoute
  '/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/presentation': typeof PresentationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/krishi-bondhu': typeof AuthenticatedKrishiBondhuRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/machines/$id': typeof AuthenticatedMachinesIdRoute
  '/_authenticated/sell/$buyerId': typeof AuthenticatedSellBuyerIdRoute
  '/_authenticated/machines/': typeof AuthenticatedMachinesIndexRoute
  '/_authenticated/sell/': typeof AuthenticatedSellIndexRoute
  '/_authenticated/sell/listing/$listingId': typeof AuthenticatedSellListingListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/presentation'
    | '/reset-password'
    | '/dashboard'
    | '/krishi-bondhu'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/schemes'
    | '/machines/$id'
    | '/sell/$buyerId'
    | '/machines/'
    | '/sell/'
    | '/sell/listing/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/presentation'
    | '/reset-password'
    | '/dashboard'
    | '/krishi-bondhu'
    | '/market'
    | '/notifications'
    | '/profile'
    | '/schemes'
    | '/machines/$id'
    | '/sell/$buyerId'
    | '/machines'
    | '/sell'
    | '/sell/listing/$listingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/presentation'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/krishi-bondhu'
    | '/_authenticated/market'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/schemes'
    | '/_authenticated/machines/$id'
    | '/_authenticated/sell/$buyerId'
    | '/_authenticated/machines/'
    | '/_authenticated/sell/'
    | '/_authenticated/sell/listing/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PresentationRoute: typeof PresentationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/krishi-bondhu': {
      id: '/_authenticated/krishi-bondhu'
      path: '/krishi-bondhu'
      fullPath: '/krishi-bondhu'
      preLoaderRoute: typeof AuthenticatedKrishiBondhuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/': {
      id: '/_authenticated/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof AuthenticatedSellIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/': {
      id: '/_authenticated/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AuthenticatedMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/$buyerId': {
      id: '/_authenticated/sell/$buyerId'
      path: '/sell/$buyerId'
      fullPath: '/sell/$buyerId'
      preLoaderRoute: typeof AuthenticatedSellBuyerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/machines/$id': {
      id: '/_authenticated/machines/$id'
      path: '/machines/$id'
      fullPath: '/machines/$id'
      preLoaderRoute: typeof AuthenticatedMachinesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/listing/$listingId': {
      id: '/_authenticated/sell/listing/$listingId'
      path: '/sell/listing/$listingId'
      fullPath: '/sell/listing/$listingId'
      preLoaderRoute: typeof AuthenticatedSellListingListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKrishiBondhuRoute: typeof AuthenticatedKrishiBondhuRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedMachinesIdRoute: typeof AuthenticatedMachinesIdRoute
  AuthenticatedSellBuyerIdRoute: typeof AuthenticatedSellBuyerIdRoute
  AuthenticatedMachinesIndexRoute: typeof AuthenticatedMachinesIndexRoute
  AuthenticatedSellIndexRoute: typeof AuthenticatedSellIndexRoute
  AuthenticatedSellListingListingIdRoute: typeof AuthenticatedSellListingListingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKrishiBondhuRoute: AuthenticatedKrishiBondhuRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedMachinesIdRoute: AuthenticatedMachinesIdRoute,
  AuthenticatedSellBuyerIdRoute: AuthenticatedSellBuyerIdRoute,
  AuthenticatedMachinesIndexRoute: AuthenticatedMachinesIndexRoute,
  AuthenticatedSellIndexRoute: AuthenticatedSellIndexRoute,
  AuthenticatedSellListingListingIdRoute:
    AuthenticatedSellListingListingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PresentationRoute: PresentationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
